import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Scoped to foundations/ only, not the docs root, so intro.mdx (the
  // default Docusaurus "Tutorial Intro" scaffold page) stays out of the left
  // nav without being excluded from the build — it's still reachable at
  // /docs/intro, which src/pages/index.tsx and HomepageModules still link to.
  tutorialSidebar: [{type: 'autogenerated', dirName: 'foundations'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
