// Generated by scripts/extract-examples.mjs, do not edit.
import f0 from './setup-install/kotlin.text';
import f1 from './setup-install/java-1.text';
import f2 from './setup-install/java-2.text';
import f3 from './setup-install/typescript.text';
import f4 from './setup-imports/kotlin.text';
import f5 from './setup-imports/typescript.text';
import f6 from './rfc9457-problem-json/json.text';
import f7 from './rfc9457-convert/kotlin.text';
import f8 from './rfc9457-convert/typescript.text';
import f9 from './rfc9457-minimal/kotlin.text';
import f10 from './rfc9457-minimal/typescript.text';
import f11 from './rfc9457-errors/kotlin.text';
import f12 from './rfc9457-errors/typescript.text';
import f13 from './rfc9457-problem/kotlin.text';
import f14 from './rfc9457-problem/typescript.text';

const files: Record<string, string> = {
  'setup-install/kotlin.text': f0,
  'setup-install/java-1.text': f1,
  'setup-install/java-2.text': f2,
  'setup-install/typescript.text': f3,
  'setup-imports/kotlin.text': f4,
  'setup-imports/typescript.text': f5,
  'rfc9457-problem-json/json.text': f6,
  'rfc9457-convert/kotlin.text': f7,
  'rfc9457-convert/typescript.text': f8,
  'rfc9457-minimal/kotlin.text': f9,
  'rfc9457-minimal/typescript.text': f10,
  'rfc9457-errors/kotlin.text': f11,
  'rfc9457-errors/typescript.text': f12,
  'rfc9457-problem/kotlin.text': f13,
  'rfc9457-problem/typescript.text': f14,
};

export default files;
