// Generated by scripts/extract-examples.mjs, do not edit.
import f0 from './setup-imports/kotlin.text';
import f1 from './setup-imports/typescript.text';
import f2 from './overview-usage/kotlin.text';
import f3 from './overview-usage/typescript.text';
import f4 from './explanation-immutable/kotlin.text';
import f5 from './explanation-immutable/typescript.text';
import f6 from './explanation-security/kotlin.text';
import f7 from './explanation-security/typescript.text';
import f8 from './explanation-parse/kotlin.text';
import f9 from './explanation-parse/typescript.text';
import f10 from './tutorial-create/kotlin.text';
import f11 from './tutorial-create/typescript.text';
import f12 from './tutorial-copy/kotlin.text';
import f13 from './tutorial-copy/typescript.text';
import f14 from './tutorial-header/kotlin.text';
import f15 from './tutorial-header/typescript.text';
import f16 from './tutorial-parse/kotlin.text';
import f17 from './tutorial-parse/typescript.text';
import f18 from './tutorial-external/kotlin.text';
import f19 from './tutorial-external/typescript.text';
import f20 from './guide-kinds/kotlin.text';
import f21 from './guide-kinds/typescript.text';
import f22 from './guide-gateway/kotlin.text';
import f23 from './guide-gateway/typescript.text';
import f24 from './guide-tags/kotlin.text';
import f25 from './guide-tags/typescript.text';
import f26 from './guide-criticality/kotlin.text';
import f27 from './guide-criticality/typescript.text';
import f28 from './guide-malformed/kotlin.text';
import f29 from './guide-malformed/typescript.text';

const files: Record<string, string> = {
  'setup-imports/kotlin.text': f0,
  'setup-imports/typescript.text': f1,
  'overview-usage/kotlin.text': f2,
  'overview-usage/typescript.text': f3,
  'explanation-immutable/kotlin.text': f4,
  'explanation-immutable/typescript.text': f5,
  'explanation-security/kotlin.text': f6,
  'explanation-security/typescript.text': f7,
  'explanation-parse/kotlin.text': f8,
  'explanation-parse/typescript.text': f9,
  'tutorial-create/kotlin.text': f10,
  'tutorial-create/typescript.text': f11,
  'tutorial-copy/kotlin.text': f12,
  'tutorial-copy/typescript.text': f13,
  'tutorial-header/kotlin.text': f14,
  'tutorial-header/typescript.text': f15,
  'tutorial-parse/kotlin.text': f16,
  'tutorial-parse/typescript.text': f17,
  'tutorial-external/kotlin.text': f18,
  'tutorial-external/typescript.text': f19,
  'guide-kinds/kotlin.text': f20,
  'guide-kinds/typescript.text': f21,
  'guide-gateway/kotlin.text': f22,
  'guide-gateway/typescript.text': f23,
  'guide-tags/kotlin.text': f24,
  'guide-tags/typescript.text': f25,
  'guide-criticality/kotlin.text': f26,
  'guide-criticality/typescript.text': f27,
  'guide-malformed/kotlin.text': f28,
  'guide-malformed/typescript.text': f29,
};

export default files;
